#!/usr/bin/env bash
# Undo node
npm uninstall -g yarn typescript-language-server typescript

# Undo zsh
uninstall_oh_my_zsh
chsh /bin/bash
sudo apt purge zsh

# Undo Core Install
sudo apt -y purge htop stow tmux build-essential wireshark golang fzf lsof python3-pip dconf-editor lua tldr
