#!/usr/bin/env bash

available_tags=("core" "install" "node" "ssh" "zsh" "dotfiles" "productivity" "git-personal" "git-hp")
echo "Available tags: ${available_tags[@]}"
read -p "Enter the tags you want to use (separated by commas): " tags

## Install ansible
sudo apt-add-repository -y ppa:ansible/ansible
sudo apt update -y
sudo apt install -y curl git software-properties-common ansible

sudo ansible-pull -U https://github.com/Fillps/ansible.git --ask-vault-pass --tags "${tags[@]}" local.yml