- name: Install ZSH
  become: yes
  apt: name=zsh
  tags: &tags_for_zsh_tasks [ 'install', 'productivity', 'dotfiles', 'zsh' ]
    
- name: Change shell to zsh
  become: yes
  shell: chsh -s $(which zsh)
  tags: *tags_for_zsh_tasks

- name: Check that the somefile.conf exists
  stat:
    path: ~/.oh-my-zsh
  register: oh_my_stats
  tags: *tags_for_zsh_tasks

- name: Oh-My-Zsh
  shell: curl -L https://raw.github.com/robbyrussell/oh-my-zsh/master/tools/install.sh > ~/.oh-my-installer && chmod +x ~/.oh-my-installer && ~/.oh-my-installer
  when: oh_my_stats.stat.exists == False
  become_user: "{{ lookup('env', 'USER') }}"
  tags: *tags_for_zsh_tasks

- name: Install zsh-autosuggestions
  ansible.builtin.git:
    repo: 'https://github.com/zsh-users/zsh-autosuggestions.git'
    dest: "~/.oh-my-zsh/plugins/zsh-autosuggestions"
  tags: *tags_for_zsh_tasks

- name: Install zsh-autocomplete
  ansible.builtin.git:
    repo: 'https://github.com/marlonrichert/zsh-autocomplete.git'
    dest: "~/.oh-my-zsh/plugins/zsh-autocomplete"
    depth: 1
    version: main
  tags: *tags_for_zsh_tasks

- name: Create .zshrc backup
  command: mv ~/.zshrc ~/.zshrc.bkp
  ignore_errors: yes
  tags: 
  - dotfiles

- name: Create .zsh_profile backup
  command: mv ~/.zsh_profile ~/.zsh_profile.bkp
  ignore_errors: yes
  tags: 
  - dotfiles

- name: Create .zshenv backup
  command: mv ~/.zshenv ~/.zshenv.bkp
  ignore_errors: yes
  tags: 
  - dotfiles